Repository BRIKEV/express-jsdoc-swagger-docs, pull requests merged in 2020-10, with the labels that each got.

#17 docs: add usage instructions for `example` annotation
  docs/_sidebar.md
  docs/assets/examples.png
  docs/es/_sidebar.md
  docs/es/examples.md
  docs/es/requestBody.md
  docs/es/responses.md
  docs/examples.md
  docs/requestBody.md
  docs/responses.md
  docs/zh/_sidebar.md
  docs/zh/examples.md
  docs/zh/requestBody.md
  docs/zh/responses.md
Labels: hacktoberfest-accepted

#19 Es lang
  docs/es/_sidebar.md
  docs/es/combineSchemas.md
  docs/es/components.md
  docs/es/configuration.md
  docs/es/eventEmitter.md
  docs/es/examples.md
  docs/es/merge.md
  docs/es/parameters.md
  docs/es/responses.md
  docs/es/tags.md
Labels: documentation, hacktoberfest-accepted

#18 Docs/form parameters
  docs/combineSchemas.md
  docs/es/examples.md
  docs/es/requestBody.md
  docs/examples.md
  docs/requestBody.md
  docs/zh/examples.md
  docs/zh/requestBody.md
Labels: hacktoberfest-accepted

#21 fix:sidebar
  docs/README.md
  docs/es/README.md
  docs/es/_sidebar.md
  docs/es/components.md
  docs/es/security.md
  docs/es/tags.md
  docs/zh/README.md
  docs/zh/_sidebar.md
Labels: bug, hacktoberfest-accepted
